# Site settings
title: Spring Blog
SEOTitle: 许泉的博客 | Spring Blog
header-img: img/home-bg.jpg
email: qxuchn@gmail.com
description: "生物信息，生物统计，计算生物 | 许泉，Web & Mobile Lover，Front-End Engineer，UX Designer | 这里是 @Spring许泉 的个人博客，与你一起发现更大的世界。"
keyword: "许泉, Spring, 许泉的博客, Spring Blog, 博客, 个人网站, 互联网, 前端, 设计, 产品, python, linux, R, shell"
url: "http://biospring.xyz"
baseurl: ""



# SNS settings
RSS: false
weibo_username:     u/5319493962
zhihu_username:     spring-xu
github_username:    bioquan
#twitter_username:  huxpro
#facebook_username:  huxpro



# Build settings
highlighter: pygments
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Duoshuo settings
duoshuo_username: springblog
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: true                     # set to false if you want to use Comment without Sharing




# Analytics settings
# Baidu Analytics
ba_track_id: 4cc1f2d8f3067386cc5cdb626a202900
# Google Analytics
ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
ga_domain: biospring.xyz



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "科学的世界这么大，怎么会没有我的地盘呢。地上的路那么多，总有一条是属于我的路。"
sidebar-avatar: /img/avatar-spring.jpg     # use absolute URL.



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Friends
friends: [
    {
        title: "天镶的博客",
        href: "http://lingyu.wang/"
    },{
        title: "SmdCn's Blog",
        href: "http://blog.smdcn.net"
    }
]
